version: '3.9'
services:
  postgres:
    container_name: stack.postgres
    image: postgres:latest
    env_file:
      - ./postgres/dev.env

  s3:
    image: localstack/localstack:latest
    container_name: stack.s3
    environment:
      - SERVICES=s3
    volumes:
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

    ports:
      - '4000:4566'

  mlflow:
    build:
      context: mlflow
    container_name: stack.mlflow
    platform: linux/amd64
    image: mlflow-core:latest
    restart: on-failure
    depends_on:
      - postgres
      - s3
    env_file:
      - ./mlflow/dev.env
    ports:
      - '80:3000'
