version: '3.9'
services:
  dynamo:
    image: amazon/dynamodb-local
    container_name: dynamodb

  flask:
    build:
      context: service
    depends_on:
      dynamo:
        condition: service_healthy
    container_name: flask
    env_file:
      - ./service/dev.env

  nginx:
    build:
      context: nginx
    container_name: nginx
    volumes:
      - ./nginx/.htpasswd:/etc/apache2/.htpasswd
      - ./html:/data/www
    ports:
      - '80:80'