version: '3.9'
services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    volumes:
      - ./nginx/.htpasswd:/etc/apache2/.htpasswd
      - ./html:/data/www
    ports:
      - '80:80'

  flask:
    build:
      context: service
    container_name: flask
