version: '3.9'
services:
  dynamo:
    image: amazon/dynamodb-local
    container_name: stack.dynamo

  postgres:
    container_name: stack.postgres
    image: postgres:latest
    env_file:
      - ./postgres/dev.env

  s3:
    image: localstack/localstack
    container_name: stack.s3
    environment:
      - SERVICES=s3
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d

  flask:
    build:
      context: service
    depends_on:
      - dynamo
    container_name: stack.flask
    restart: on-failure
    env_file:
      - ./service/dev.env
    volumes:
      - ./service/authenticator:/opt/authenticator
      - ./service/tests:/opt/tests

  mlflow:
    build:
      context: mlflow
    container_name: stack.mlflow
    image: custom-mlflow:latest
    restart: on-failure
    depends_on:
      - postgres
      - s3
    env_file:
      - ./mlflow/dev.env

  nginx:
    build:
      context: nginx
    container_name: stack.nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'